# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Busca CEP. Santa Inês - MA"
email: nilsonlinux@gmail.com
description: "Fazendo um sistema de busca simples no Jekyll usando AngularJS"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://buscacepsi.github.io" # the base hostname & protocol for your site
twitter_username: nilsonlinux
github_username:  nilsonlinux

# Build settings
markdown: kramdown
